In [0]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr_1 = np.array(range(10,15))
arr_1

array([10, 11, 12, 13, 14])

In [2]:
obj = Series(range(10,15))
obj

0    10
1    11
2    12
3    13
4    14
dtype: int64

In [4]:
type(obj)

pandas.core.series.Series

In [6]:
type(obj.values)

numpy.ndarray

In [7]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
type(obj.index)

pandas.core.indexes.range.RangeIndex

In [0]:
type(obj), type(obj.values), type(obj.index)

In [9]:
obj.values

array([10, 11, 12, 13, 14])

In [10]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [15]:
obj1 = Series([10,3,40,50], index= ['H1', 'H2', 'H3', 'H4'])
obj1

H1    10
H2     3
H3    40
H4    50
dtype: int64

In [16]:
obj1['H4']

50

In [18]:
obj1[3]

50

In [0]:
from pandas import date_range

In [0]:
obj1 = Series(10 + np.arange(100),
              index= [date_range(start='1/1/2018', 
                                 periods=100, 
                                 freq='M')])

In [47]:
obj1

2018-01-31     10
2018-02-28     11
2018-03-31     12
2018-04-30     13
2018-05-31     14
             ... 
2025-12-31    105
2026-01-31    106
2026-02-28    107
2026-03-31    108
2026-04-30    109
Length: 100, dtype: int64

In [48]:
obj1["2026-03-31"]

2026-03-31    108
dtype: int64

In [45]:
obj1.index[80]

(Timestamp('2018-03-22 00:00:00', freq='D'),)

In [87]:
obj1 = Series([10,3,40,50], index= ['A', 'B', 'C', 'D'])
obj1

A    10
B     3
C    40
D    50
dtype: int64

In [55]:
obj1[(obj1 > 20) & (obj1 < 300)]

C    40
D    50
dtype: int64

In [52]:
obj1 < 30

A     True
B     True
C    False
D    False
dtype: bool

In [59]:
10 in obj1.values

True

In [0]:
d1 = {}
d1["H1"] = 5
d1["H2"] = 10

In [62]:
"H2" in d1

True

In [0]:
obj1[(obj1 > 30) & (obj1 < 60)]

In [0]:
obj1[obj1>30]

In [0]:
'C' in obj1

In [63]:
# Converting series to dictionary
obj1_dict = obj1.to_dict()
obj1_dict

{'A': 10, 'B': 3, 'C': 40, 'D': 50}

In [0]:
import json

In [65]:
json.dumps(obj1_dict)

'{"A": 10, "B": 3, "C": 40, "D": 50}'

In [0]:
import yaml

In [68]:
yaml.dump(obj1_dict)

'{A: 10, B: 3, C: 40, D: 50}\n'

In [0]:
# Converting from dict to series
obj1_from_dict = Series(obj1_dict)
obj1_from_dict

In [71]:
obj1

A    10.0
B     3.0
C    40.0
D     NaN
dtype: float64

In [0]:
obj1["D"] = np.nan

In [91]:
type(None)

NoneType

In [89]:
obj1

A    10.0
B     3.0
C    40.0
D     NaN
dtype: float64

In [84]:
obj1.isnull()

A    False
B    False
C    False
D     True
dtype: bool

In [75]:

obj1.shape[0] - obj1.notnull().sum()

1

In [77]:
obj1.isnull().sum()

1

In [0]:
s1 = Series([1,2,3,4],index=['a','b','c','d'])
s2 = Series([5,6,7,8],index=['a','b','c','e'])

In [93]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [94]:
s2

a    5
b    6
c    7
e    8
dtype: int64

In [96]:
np.nan + 45

nan

In [0]:
s3 = s1 + s2

In [98]:
s3

a     6.0
b     8.0
c    10.0
d     NaN
e     NaN
dtype: float64

In [0]:
s3.replace(np.nan, 85, inplace=True)

In [102]:
s3

a     6.0
b     8.0
c    10.0
d    85.0
e    85.0
dtype: float64

In [0]:
obj2 = obj1.add(obj1_from_dict)
obj2

In [0]:
s1 = Series([1,2,3,4],index=['a','b','c','d'])
s2 = Series([1,2,3,4],index=['a','b','c','e'])
s3 = s1+s2
s3

In [0]:
# Replacing Values in a Series
s3.replace(np.nan, 10)

In [0]:
s3 = s3.replace(2.0, 10.0)
s3

In [0]:
s3.values

In [0]:
s3.replace(np.nan, 9.0)

In [0]:
s3.replace(np.nan, 9.5, inplace=True)

In [0]:
s3.replace(10.0, 7.0, inplace=True)

In [0]:
s3.replace(7.0, 'Bhavesh', inplace=True)

In [103]:
s3

a     6.0
b     8.0
c    10.0
d    85.0
e    85.0
dtype: float64

In [0]:
s3[['a','b']] = 'Idli'

In [110]:
s3.values

array(['Idli', 'Idli', 10.0, 85.0, 85.0], dtype=object)

In [0]:
init_arry = np.arange(9).reshape((3,3))

In [112]:
init_arry

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
s1 = Series([1, 2], index=['A', 'B'], name='s1')
s2 = Series([3, 4, 5], index=['A', 'D', 'C'], name='s2')

In [0]:
d1 = pd.DataFrame(s1 + s2)

In [148]:
d1.shape

(4, 1)

In [144]:
pd.concat([s1, s2], axis=1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


s1   s2
A  1.0  3.0
B  2.0  NaN
C  NaN  5.0
D  NaN  4.0

In [0]:
df1 = pd.DataFrame(s1)

In [135]:
df1

s1
A   1
B   2

In [0]:
arr_1 = np.arange(0,5).reshape(5,1)
arr_2 = np.arange(10,15).reshape(5,1)


In [141]:
(arr_1 + arr_2).shape

(5, 1)

In [130]:
s10 = pd.concat([s1, s2], axis =1 )

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [131]:
s10

s1   s2
A  1.0  3.0
B  2.0  NaN
C  NaN  5.0
D  NaN  4.0

In [122]:
s1

A    1
B    2
Name: s1, dtype: int64

In [123]:
s2

A    3
D    4
Name: s2, dtype: int64

In [0]:
s4 = pd.concat([s1,s2], axis=0)

In [128]:
s4["A"].values[0]

1

In [0]:
s1

In [0]:
s3

In [0]:
s1 = Series([1, 2], index=['A', 'B'], name='s1')
s2 = Series([3, 4], index=['C', 'D'], name='s2')
print (s1)
print (s2)

In [0]:
s3 = pd.concat([s1, s2], axis=0)
s3

In [0]:
s3['A']

In [0]:
type(s3)

In [0]:
s4 = pd.concat([s1, s2], axis=1)
s4

In [0]:
type(s4)